### ISSUE TITLE
Be rootlesson mda images

### ISSUE THREAD

**Issue by paulsouche** [SocialGouv/mda#236]
getmeili/meilisearch:1.1.0, debian:buster are not rootless images.

This ticket implies
 - Try to run the meilisearch image not in root mode and eventually create a new image
 - Mount files rootless on azure volume (to be able to delete the files) and change the debian image
 
 Example of mount
 ```yml
   volumes:
    - name: ftp-files
      csi:
        driver: file.csi.azure.com
        readOnly: false
        volumeAttributes:
          secretName: ftp-share
          secretNamespace: ftp-test
          shareName: ftp
          mountOptions: "uid=1001"
 ```
 
 More [here](https://github.com/SocialGouv/manifests/blob/433bcdc80d5514eb48c006a6c9a8fb144817728d/pureftpd/projects/test/dev/values.yaml#L26)
